In [1]:
import numpy as np
import math

In [78]:
#задание 1
def result_mark(weights: np.array, marks: np.array) -> int:
  m = marks.shape[0]
  fin = 0
  for i in range(m):
    fin=fin+(weights[i]*marks[i])
  fin = round(fin)
  return fin


In [80]:
# задание 2
def change_array(array: np.array, number: int) -> np.array:
    m = array.shape[0]
    for i in range(m):
      if (i == 0) or ((i)%3 == 0):
        array[i] = number
    return array


In [33]:
# задание 3
import math
array1 = np.array([1.5, 0.5, 2, -4.1, -3, 6, -1])
array2 = np.array([1.2, 0.5, 1, -4.0,  3, 0, -1.2])
precision = 0.5


mylist = []
m = array1.shape[0]
for i in range(m):
  if math.fabs(array1[i] - array2[i]) <= precision:
    mylist.append(i)
mat = np.array(mylist)
print(mat)


[0, 1, 3, 6]
[0 1 3 6]


In [74]:
# задание 4
block = np.array([[1, 3, 3], [7, 0, 0]])



l = np.zeros(shape=(block.shape[0]*2,block.shape[1]*2))
for i in range(block.shape[0]):
  for j in range(block.shape[1]):
    l[i][j]=block[i][j]
for i in range(block.shape[0]):
  for j in range(block.shape[1]):
    l[i+block.shape[0]][j+block.shape[1]]=l[i][j]
    l[i][j+block.shape[1]]=l[i][j]
    l[i+block.shape[0]][j]=l[i][j]
l

array([[1., 3., 3., 1., 3., 3.],
       [7., 0., 0., 7., 0., 0.],
       [1., 3., 3., 1., 3., 3.],
       [7., 0., 0., 7., 0., 0.]])

In [35]:
# задание 5
matrix = np.array([[0, 1, 2, 3],
                   [4, 5, 6, 7],
                   [8, 9, 10, 11],
                   [12, 13, 14, 15]])



x=1
m = matrix.shape[0]
for i in range(m):
  if matrix[i][i]!=0:
    x=x*matrix[i][i]
print(x)

750


In [39]:
# задание 8
matrix = np.array([[10, 21, 32, 49], [0, 53, 62, 78], [0, 0, 82, 92], [0, 0, 0, 10]])




m = matrix.shape[0]
for i in range(m):
  for j in range(m):
    if i>j:
      matrix[i][j]=matrix[j][i]
matrix

In [47]:
# Задание 9

m = 6
a = 7
b = 11




l = np.zeros(shape=(m,b-a+1))
for j in range(b-a+1):
  for i in range(m):
    l[i][j]=a+j
l

array([[ 7.,  8.,  9., 10., 11.],
       [ 7.,  8.,  9., 10., 11.],
       [ 7.,  8.,  9., 10., 11.],
       [ 7.,  8.,  9., 10., 11.],
       [ 7.,  8.,  9., 10., 11.],
       [ 7.,  8.,  9., 10., 11.]])

In [48]:
# Задание 10
vec1 = np.array([-2, 1,  0, -5, 4, 3, -3])
vec2 = np.array([ 0, 2, -2, 10, 6, 0,  0])




sum1 = 0
sum2 = 0
sum3 = 0
m = vec1.shape[0]
for i in range(m):
  sum1=sum1+(vec1[i]*vec2[i])
for i in range(m):
  sum2 = sum2+(vec1[i]*vec1[i])
  sum3 = sum3+(vec2[i]*vec2[i])
res = sum1/(math.sqrt(sum2)*math.sqrt(sum3))
res
